'''
The mapping template is a dictionary with either imbeded lists of columns or dictionaries
that allow for specific mapping and reporting fuctions. If a field category is a list "[None]"
then add the fields names exactly as they appear in the table or found in the describe report.
The reference_fields are used for context. This set of fields is used in the dataframe to join 
back to the fields that will go through the evalution.
'''

# COPY AND PASTE THIS TEMPLATE AND RENAME FOR THE TABLE YOU ADD

mapping_template = {
    'db_schema':[
        'name_of_schema'
    ],
    'db_table':[
        'name_of_database_table'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        'id required',
        'addtional_ids'
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':'FULLADDRESS',
                'address1':'ADDRESS1',
                'address2':'ADDRESS2',
                'address3':'ADDRESS3',
                'city':'CITY',
                'state':'STATE',
                'postal_code':'ZIPCODE',
                'country':'COUNTRY'
            },
            'address2':{
                'address_root_name':'contact2',
                'full_address':'FULLADDRESS2',
                'address1':'ADDRESS1_2',
                'address2':'ADDRESS2_2',
                'address2':'ADDRESS3_2',                
                'city':'CITY_2',
                'state':'STATE_2',
                'postal_code':'ZIPCODE_2',
                'country':'COUNTRY_2'
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        None
    ]
}


hubspot = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'Hubspot'
    ],
    'db_primary_key':[
        'Record ID'   
    ],
    'excel_sheet':[
        'All companies'
    ],
    'reference_fields':[
         'Account Name'
    ],
    'default_country_field':[
        'Country'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'Account Name'
    ],
    'isNull':[
        'Street Address',
        'Postal Code',
        'City',
        'State/Region'
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'hubspot',
                'full_address':None,
                'address1':'Street Address',
                'address2':'Street Address 2',
                'address3':None,
                'city':'City',
                'state':'State/Region',
                'postal_code':'Postal Code',
                'country':'Country'
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        None
    ]
}


non_closedwon_address_phone_email_view = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'Non_ClosedWon_Address_Phone_and_Email_View'
    ],
    'db_primary_key':[
        'contact id'   
    ],
    'reference_fields':[
         'customer_id',
         'contact address id'
    ],
    'default_country_field':[
        'country'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'email'
    ],
    'isNull':[
        'leadprospectname',
        'firstname',
        'lastname',
        'email',
        'addr1',
        'zip'
    ],
    'address':{
        'hasAddress':None,
        'addresses':{
            'address1':{
                'address_root_name':'non_customer',
                'full_address':None,
                'address1':'addr1',
                'address2':'addr2',
                'address3':None,
                'city':'city',
                'state':'state',
                'postal_code':'zip',
                'country':'country'
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        'email'
    ],
    'url':[
        None
    ],
    'name':[
        'firstname',
        'lastname'
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        None
    ]
}

non_closedwon_addresses_view = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'Non_Customer_Addresses_View'
    ],
    'db_primary_key':[
        'id'   
    ],
    'reference_fields':[
        'custentity_tp_zi_id'
    ],
    'default_country_field':[
        'country'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'ap_email'
    ],
    'isNull':[
        'leadprospectname',
        'ap_email',
        'addr1',
        'city',
        'state',
        'zip'
    ],
    'address':{
        'hasAddress':None,
        'addresses':{
            'address1':{
                'address_root_name':'non_customer',
                'full_address':None,
                'address1':'addr1',
                'address2':'addr2',
                'address3':None,
                'city':'city',
                'state':'state',
                'postal_code':'zip',
                'country':'country'
            }
        }
    },
    'phone':[
        'homephone',
        'phone'
    ],
    'email':[
        'ap_email'
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        'homephone'
    ]
}


mdm_contact__active = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'MDM_Contact__Active'
    ],
    'db_primary_key':[
        'id'   
    ],
    'reference_fields':[
        'Datasource ID'
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'Email_1'
    ],
    'isNull':[
        'First Name',
        'Last_Name',
        'Email_1'
    ],
    'address':{
        'hasAddress':None,
        'addresses':{
            'address1':{
                'address_root_name':'default',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        'Phone_Number_1',
        'Phone_Number_2'
    ],
    'email':[
        'Email_1'
    ],
    'url':[
        None
    ],
    'name':[
        'First Name',
        'Last_Name'
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        'Phone_Number_2'
    ]
}

mdm_customer__active = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'MDM_Customer__Active'
    ],
    'db_primary_key':[
        'id'   
    ],
    'reference_fields':[
        'Datasource ID'
    ],
    'default_country_field':[
        'Country Code'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'Company Name'
    ],
    'isNull':[
        'Company Name',
        'Address 1',
        'City',
        'State',
        'Postal Code',
        'Country Code',
        'AE/AM/ISR First Name',
        'AE/AM/ISR Last name',
        'SSA First Name',
        'SSA Last Name'
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':'Address 1',
                'address2':'Address 2',
                'address3':None,
                'city':'City',
                'state':'State',
                'postal_code':'Postal Code',
                'country':'Country Code'
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        'Website / URL'
    ],
    'name':[
      'AE/AM/ISR First Name',
      'AE/AM/ISR Last name',
      'SSA First Name',
      'SSA Last Name'
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        'Website / URL'
    ]
}


mdm_contact__active_view = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'MDM_Contact__Active_View'
    ],
    'db_primary_key':[
        'id'   
    ],
    'reference_fields':[
        'Datasource ID'
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'Email_1'
    ],
    'isNull':[
        'First Name',
        'Last_Name',
        'Email_1'
    ],
    'address':{
        'hasAddress':None,
        'addresses':{
            'address1':{
                'address_root_name':'default',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        'Phone_Number_1',
        'Phone_Number_2'
    ],
    'email':[
        'Email_1'
    ],
    'url':[
        None
    ],
    'name':[
        'First Name',
        'Last_Name'
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        'Phone_Number_2'
    ]
}

mdm_customer__active_view = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'MDM_Customer__Active_View'
    ],
    'db_primary_key':[
        'id'   
    ],
    'reference_fields':[
        'Datasource ID'
    ],
    'default_country_field':[
        'Country Code'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'Company Name'
    ],
    'isNull':[
        'Company Name',
        'Address 1',
        'City',
        'State',
        'Postal Code',
        'Country Code',
        'AE/AM/ISR First Name',
        'AE/AM/ISR Last name',
        'SSA First Name',
        'SSA Last Name'
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':'Address 1',
                'address2':'Address 2',
                'address3':None,
                'city':'City',
                'state':'State',
                'postal_code':'Postal Code',
                'country':'Country Code'
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        'Website / URL'
    ],
    'name':[
      'AE/AM/ISR First Name',
      'AE/AM/ISR Last name',
      'SSA First Name',
      'SSA Last Name'
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        'Website / URL'
    ]
}

gp_CustomerAddresses = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'GreatPlains_Customer_Addresses'
    ],
    'db_primary_key':[
        'DEX_ROW_ID'   
    ],
    'reference_fields':[
        'CUSTNMBR'
    ],
    'default_country_field':[
        'CCode'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'ShipToName',
        'CUSTNMBR'
    ],
    'isNull':[
        'ShipToName',
        'ADDRESS1',
        'CITY',
        'STATE',
        'ZIP',
        'CCode',
        'ShipToName'
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'default',
                'full_address':None,
                'address1':'ADDRESS1',
                'address2':'ADDRESS2',
                'address3':'ADDRESS3',
                'city':'CITY',
                'state':'STATE',
                'postal_code':'ZIP',
                'country':'CCode'
            }
        }
    },
    'phone':[
        'PHONE1',
        'PHONE2',
        'PHONE3'
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}

customer_cols = {
    'reference_fields':[
        'CUSTOMER_ID'
    ],
    'default_country_field':[
        'COUNTRY'
    ],
    'db_primary_key':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'CompanyName'
    ],
    'isNull':[
        'CompanyName',
        'CITY',
        'STATE',
        'COUNTRY',
        'ZIPCODE'
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':'FULLADDRESS',
                'address1':'ADDRESS1',
                'address2':'ADDRESS2',
                'address3':'ADDRESS3',
                'city':'CITY',
                'state':'STATE',
                'postal_code':'ZIPCODE',
                'country':'COUNTRY'
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}



gp_CustomerMaster = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'GreatPlains_Customer_Master'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        'CUSTNMBR',
        'DEX_ROW_ID'
    ],
    'default_country_field':[
        'CCode'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'ShipToName'
    ],
    'isNull':[
        'ADDRESS1',
        'ADDRESS2',
        'ADDRESS3',
        'CITY',
        'STATE',
        'ZIP',
        'CCode',
        'ShipToName'
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':'ADDRESS1',
                'address2':'ADDRESS2',
                'address3':'ADDRESS3',
                'city':'CITY',
                'state':'STATE',
                'postal_code':'ZIP',
                'country':'CCode'
            }
        }
    },
    'phone':[
        'PHONE1',
        'PHONE2',
        'PHONE3'
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_contact_phone = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Contact_Phone'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_contact_email = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Contact_Email'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_contact_address = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Contact_Address'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_contact_account_link = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Contact_Account_Link'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_contact = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Contact'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_company_status = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Company_Status'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_company_source = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Company_Source'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_company_name_type = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Company_Name_Type'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_company_source_sys_type = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Company_Source_System_Type'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_company_accting_mapping = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Company_Accounting_Mapping'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


tpdb_company = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'TPDB_Company'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}

snow_contact = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'Snow_Contact'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


snow_company = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'Snow_Company'
    ],
    'reference_fields':[
        None
    ],
    'db_primary_key':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}


snow_account = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'Snow_Account'
    ],
    'db_primary_key':[
        None
    ],
    'reference_fields':[
        None
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        None
    ],
    'name':[
        None
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}

ns_customers = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'NetSuite2_Customers'
    ],
    'db_primary_key':[
        'entityid'
    ],
    'reference_fields':[
        'entityid'
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        None
    ],
    'email':[
        None
    ],
    'url':[
        'url'
    ],
    'name':[
        'firstname',
        'lastname'
    ],
    'z_num_outliers':[
        'custentity_emailsdelivered'
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ]
}

ns_contacts = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'NetSuite2_Contacts'
    ],
    'db_primary_key':[
        'company'
    ],
    'reference_fields':[
        'company'
    ],
    'default_country_field':[
        None
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        None
    ],
    'isNull':[
        None
    ],
    'address':{
        'hasAddress':False,
        'addresses':{
            'address1':{
                'address_root_name':'contact',
                'full_address':None,
                'address1':None,
                'address2':None,
                'address3':None,
                'city':None,
                'state':None,
                'postal_code':None,
                'country':None
            }
        }
    },
    'phone':[
        'mobilephone',
        'phone'
    ],
    'email':[
        'email'
    ],
    'url':[
        None
    ],
    'name':[
        'firstname',
        'lastname'
    ],
    'z_num_outliers':[
        'custentity_tp_contact_buyer_persona'
    ],
    'iq_num_outliers':[
        'custentity_tp_contact_buyer_persona'
    ],
    'date_outliers':[
        'custentity_tp_dw_crat_dt_nurtr_set'
    ]
}

# Mapping for Logistics_DQPilot_CONTACT CSV dataset
logistics_dqpilot_contact = {
    'db_schema':[
        'db_replica'
    ],
    'db_table':[
        'Logistics_DQPilot_CONTACT'
    ],
    'db_primary_key':[
        'ID'
    ],
    'reference_fields':[
        'ACCOUNTID'
    ],
    'default_country_field':[
        'COUNTRY__C'
    ],
    'default_country_code':[
        'US'
    ],
    'duplicates':[
        'EMAIL'
    ],
    'isNull':[
        'FIRSTNAME',
        'LASTNAME',
        'EMAIL',
        'ADDRESS_LINE_1__C',
        'CITY__C',
        'STATE__C',
        'POSTAL_CODE__C'
    ],
    'address':{
        'hasAddress':True,
        'addresses':{
            'address1':{
                'address_root_name':'business',
                'full_address':None,
                'address1':'ADDRESS_LINE_1__C',
                'address2':'ADDRESS_LINE_2__C',
                'address3':'ADDRESS_LINE_3__C',
                'city':'CITY__C',
                'state':'STATE__C',
                'postal_code':'POSTAL_CODE__C',
                'country':'COUNTRY__C'
            },
            'mailing':{
                'address_root_name':'mailing',
                'full_address':None,
                'address1':'MAILINGSTREET',
                'address2':None,
                'address3':None,
                'city':'MAILINGCITY',
                'state':'MAILINGSTATE',
                'postal_code':'MAILINGPOSTALCODE',
                'country':'MAILINGCOUNTRY'
            },
            'other':{
                'address_root_name':'other',
                'full_address':None,
                'address1':'OTHERSTREET',
                'address2':None,
                'address3':None,
                'city':'OTHERCITY',
                'state':'OTHERSTATE',
                'postal_code':'OTHERPOSTALCODE',
                'country':'OTHERCOUNTRY'
            }
        }
    },
    'phone':[
        'PHONE',
        'MOBILEPHONE',
        'HOMEPHONE',
        'ASSISTANTPHONE',
        'OTHERPHONE',
        'FAX'
    ],
    'email':[
        'EMAIL',
        'ALTERNATE_EMAIL_ADDRESS__C'
    ],
    'url':[
        'LINKEDIN__C',
        'FACEBOOK__C',
        'TWITTER__C'
    ],
    'name':[
        'FIRSTNAME',
        'LASTNAME',
        'MIDDLE_NAME__C'
    ],
    'z_num_outliers':[
        None
    ],
    'iq_num_outliers':[
        None
    ],
    'date_outliers':[
        None
    ],
    'exception_from_row_validation':[
        None
    ]
}

